export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-indigo-400 bg-red-40" style={{
          backgroundColor : "aliceblue",
          height : "10vh"
        }}>Header</header>
        {children}
        <footer style={{
          backgroundColor : "GrayText",
          height : "10vh"
        }}>Footer</footer>
        </body>
    </html>
  )
}
